/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import crudescola.GerenciadorAlunos;
import crudescola.GerenciadorCoordenadores;
import crudescola.GerenciadorDiretor;
import crudescola.GerenciadorProfessores;
import crudescola.GerenciadorTurmas;

/**
 *
 * @author vinic
 */
public class Leituras extends javax.swing.JFrame {

    /**
     * Creates new form Leituras
     */
    GerenciadorProfessores professores;
    GerenciadorCoordenadores coordenadores;
    GerenciadorDiretor diretores;
    GerenciadorAlunos alunos;
    GerenciadorTurmas turmas;
    public Leituras() {
        initComponents();
    }
    public void listas(GerenciadorProfessores professores, GerenciadorCoordenadores coordenadores,
                     GerenciadorDiretor diretores, GerenciadorAlunos alunos, GerenciadorTurmas turmas){
        this.professores=professores;
        this.diretores=diretores;
        this.coordenadores=coordenadores;
        this.alunos=alunos;
        this.turmas=turmas;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnLerProf = new javax.swing.JButton();
        btnLerCoord = new javax.swing.JButton();
        btnLerDiretor = new javax.swing.JButton();
        btnLerAluno = new javax.swing.JButton();
        btnLerTurma = new javax.swing.JButton();
        btnVoltarLeituras = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Tela de leituras");

        btnLerProf.setText("Professor");
        btnLerProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLerProfActionPerformed(evt);
            }
        });

        btnLerCoord.setText("Coordenador");
        btnLerCoord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLerCoordActionPerformed(evt);
            }
        });

        btnLerDiretor.setText("Diretor");
        btnLerDiretor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLerDiretorActionPerformed(evt);
            }
        });

        btnLerAluno.setText("Aluno");
        btnLerAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLerAlunoActionPerformed(evt);
            }
        });

        btnLerTurma.setText("Turma");
        btnLerTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLerTurmaActionPerformed(evt);
            }
        });

        btnVoltarLeituras.setText("Voltar");
        btnVoltarLeituras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarLeiturasActionPerformed(evt);
            }
        });

        jLabel2.setText("Selecione quem você deseja visualizar:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(124, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnLerAluno)
                        .addGap(71, 71, 71)
                        .addComponent(btnLerTurma)
                        .addGap(141, 141, 141))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnVoltarLeituras)
                        .addGap(26, 26, 26))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(btnLerProf)
                        .addGap(35, 35, 35)
                        .addComponent(btnLerCoord)
                        .addGap(38, 38, 38)
                        .addComponent(btnLerDiretor))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(138, 138, 138))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(59, 59, 59)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLerProf)
                    .addComponent(btnLerCoord)
                    .addComponent(btnLerDiretor))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLerTurma)
                    .addComponent(btnLerAluno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addComponent(btnVoltarLeituras)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLerCoordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLerCoordActionPerformed
        Coordenadores coord = new Coordenadores();
        coord.setVisible(true);
    }//GEN-LAST:event_btnLerCoordActionPerformed

    private void btnLerDiretorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLerDiretorActionPerformed
        Diretores diret = new Diretores();
        diret.setVisible(true);
    }//GEN-LAST:event_btnLerDiretorActionPerformed

    private void btnLerAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLerAlunoActionPerformed
        Alunos alun = new Alunos();
        alun.alunos(alunos);
        alun.setVisible(true);
    }//GEN-LAST:event_btnLerAlunoActionPerformed

    private void btnLerTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLerTurmaActionPerformed
        Turmas turm = new Turmas();
        turm.setVisible(true);
    }//GEN-LAST:event_btnLerTurmaActionPerformed

    private void btnVoltarLeiturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarLeiturasActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVoltarLeiturasActionPerformed

    private void btnLerProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLerProfActionPerformed
        Professores prof = new Professores();
        prof.setVisible(true);
    }//GEN-LAST:event_btnLerProfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Leituras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Leituras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Leituras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Leituras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Leituras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLerAluno;
    private javax.swing.JButton btnLerCoord;
    private javax.swing.JButton btnLerDiretor;
    private javax.swing.JButton btnLerProf;
    private javax.swing.JButton btnLerTurma;
    private javax.swing.JButton btnVoltarLeituras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
